name: black_jack
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/A4.png
    - assets/Q2.png
    - assets/Q1.png
    - assets/Q4.png
    - assets/Q3.png
    - assets/10.2.png
    - assets/10.1.png
    - assets/10.4.png
    - assets/10.3.png
    - assets/2.2.png
    - assets/2.1.png
    - assets/2.4.png
    - assets/2.3.png
    - assets/3.2.png
    - assets/3.1.png
    - assets/3.4.png
    - assets/3.3.png
    - assets/4.2.png
    - assets/4.1.png
    - assets/4.4.png
    - assets/4.3.png
    - assets/5.2.png
    - assets/5.1.png
    - assets/5.4.png
    - assets/5.3.png
    - assets/6.2.png
    - assets/6.1.png
    - assets/6.4.png
    - assets/6.3.png
    - assets/7.2.png
    - assets/7.1.png
    - assets/7.4.png
    - assets/7.3.png
    - assets/8.2.png
    - assets/8.1.png
    - assets/8.4.png
    - assets/8.3.png
    - assets/9.2.png
    - assets/9.1.png
    - assets/9.4.png
    - assets/9.3.png
    - assets/A2.png
    - assets/A1.png
    - assets/A3.png
    - assets/J2.png
    - assets/J1.png
    - assets/J4.png
    - assets/J3.png
    - assets/K2.png
    - assets/K1.png
    - assets/K4.png
    - assets/K3.png
